repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md,markdown
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: chart/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=79
        exclude: tests/
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=79
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args:
          - --ignore-missing-imports
          - --scripts-are-modules
          - --allow-untyped-decorators
          - --strict
          - --allow-subclassing-any
        require_serial: true
        exclude: tests/
        additional_dependencies:
          - 'pydantic'
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.8.1
    hooks:
      - id: pylint
        types: [ python ]
        args:
          - --max-line-length=79
          - --errors-only
          - --disable=import-error,no-name-in-module
